### ISSUE TITLE
New draft: Open science and open science

### ISSUE THREAD

**Issue by lgatto** [lgatto/lgatto.github.io#9]
I have just posted a new draft post titled [Open science and open science](https://github.com/lgatto/lgatto.github.io/blob/master/_drafts/2017-06-05-open-and-open.md), which results from [this comment](https://github.com/OpenConCam/OpenConCam/issues/11#issuecomment-306059240). 

@corinalogan - it's the post I mentioned during today's OpenConCam lunch meeting - I added a reference to the #OpenGlobalSouth thread you reminded me of. 

@cbahlai - if you have time, I would be happy if you provide some feedback in this issue. Or, if you prefer, you could comment once it is published. And it you don't have time, not worries, of course. Thank you for initiating this reflection.

**Comment by cbahlai** [comment]
This is fantastic- I'll see if I can dig deeper in a bit, but this, I think, will help people feel heard and move forward in a positive direction

**Comment by corinalogan** [comment]
Nice work @lgatto! I would be really excited if OpenCon Cambridge had this as the theme this year.

**Comment by lgatto** [comment]
Thank you both for your replies. I have [published the post](https://lgatto.github.io/open-and-open/) now.
